// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/jock.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitService_ListCommits_FullMethodName        = "/jock.GitService/ListCommits"
	GitService_ListBranches_FullMethodName       = "/jock.GitService/ListBranches"
	GitService_GetCommitDetails_FullMethodName   = "/jock.GitService/GetCommitDetails"
	GitService_GetFileDiff_FullMethodName        = "/jock.GitService/GetFileDiff"
	GitService_GetStatus_FullMethodName          = "/jock.GitService/GetStatus"
	GitService_Pull_FullMethodName               = "/jock.GitService/Pull"
	GitService_ListRemotes_FullMethodName        = "/jock.GitService/ListRemotes"
	GitService_ListRemoteBranches_FullMethodName = "/jock.GitService/ListRemoteBranches"
	GitService_ExecuteDSL_FullMethodName         = "/jock.GitService/ExecuteDSL"
	GitService_DSLAutoComplete_FullMethodName    = "/jock.GitService/DSLAutoComplete"
	GitService_StageFiles_FullMethodName         = "/jock.GitService/StageFiles"
	GitService_UnstageFiles_FullMethodName       = "/jock.GitService/UnstageFiles"
	GitService_CreateCommit_FullMethodName       = "/jock.GitService/CreateCommit"
	GitService_GetWorkingDiff_FullMethodName     = "/jock.GitService/GetWorkingDiff"
	GitService_Push_FullMethodName               = "/jock.GitService/Push"
	GitService_Merge_FullMethodName              = "/jock.GitService/Merge"
	GitService_CreateBranch_FullMethodName       = "/jock.GitService/CreateBranch"
	GitService_DeleteBranch_FullMethodName       = "/jock.GitService/DeleteBranch"
	GitService_Blame_FullMethodName              = "/jock.GitService/Blame"
	GitService_GetConflictDetails_FullMethodName = "/jock.GitService/GetConflictDetails"
	GitService_ResolveConflict_FullMethodName    = "/jock.GitService/ResolveConflict"
	GitService_AbortMerge_FullMethodName         = "/jock.GitService/AbortMerge"
	GitService_IsMerging_FullMethodName          = "/jock.GitService/IsMerging"
	GitService_ListStashes_FullMethodName        = "/jock.GitService/ListStashes"
	GitService_CreateStash_FullMethodName        = "/jock.GitService/CreateStash"
	GitService_ApplyStash_FullMethodName         = "/jock.GitService/ApplyStash"
	GitService_PopStash_FullMethodName           = "/jock.GitService/PopStash"
	GitService_DropStash_FullMethodName          = "/jock.GitService/DropStash"
	GitService_ShowStash_FullMethodName          = "/jock.GitService/ShowStash"
)

// GitServiceClient is the client API for GitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitServiceClient interface {
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error)
	GetCommitDetails(ctx context.Context, in *GetCommitDetailsRequest, opts ...grpc.CallOption) (*GetCommitDetailsResponse, error)
	GetFileDiff(ctx context.Context, in *GetFileDiffRequest, opts ...grpc.CallOption) (*GetFileDiffResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	ListRemotes(ctx context.Context, in *ListRemotesRequest, opts ...grpc.CallOption) (*ListRemotesResponse, error)
	ListRemoteBranches(ctx context.Context, in *ListRemoteBranchesRequest, opts ...grpc.CallOption) (*ListRemoteBranchesResponse, error)
	ExecuteDSL(ctx context.Context, in *ExecuteDSLRequest, opts ...grpc.CallOption) (*ExecuteDSLResponse, error)
	DSLAutoComplete(ctx context.Context, in *DSLAutoCompleteRequest, opts ...grpc.CallOption) (*DSLAutoCompleteResponse, error)
	StageFiles(ctx context.Context, in *StageFilesRequest, opts ...grpc.CallOption) (*StageFilesResponse, error)
	UnstageFiles(ctx context.Context, in *UnstageFilesRequest, opts ...grpc.CallOption) (*UnstageFilesResponse, error)
	CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error)
	GetWorkingDiff(ctx context.Context, in *GetWorkingDiffRequest, opts ...grpc.CallOption) (*GetWorkingDiffResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	Merge(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeResponse, error)
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	DeleteBranch(ctx context.Context, in *DeleteBranchRequest, opts ...grpc.CallOption) (*DeleteBranchResponse, error)
	Blame(ctx context.Context, in *BlameRequest, opts ...grpc.CallOption) (*BlameResponse, error)
	GetConflictDetails(ctx context.Context, in *GetConflictDetailsRequest, opts ...grpc.CallOption) (*GetConflictDetailsResponse, error)
	ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error)
	AbortMerge(ctx context.Context, in *AbortMergeRequest, opts ...grpc.CallOption) (*AbortMergeResponse, error)
	IsMerging(ctx context.Context, in *IsMergingRequest, opts ...grpc.CallOption) (*IsMergingResponse, error)
	ListStashes(ctx context.Context, in *ListStashesRequest, opts ...grpc.CallOption) (*ListStashesResponse, error)
	CreateStash(ctx context.Context, in *CreateStashRequest, opts ...grpc.CallOption) (*CreateStashResponse, error)
	ApplyStash(ctx context.Context, in *ApplyStashRequest, opts ...grpc.CallOption) (*ApplyStashResponse, error)
	PopStash(ctx context.Context, in *PopStashRequest, opts ...grpc.CallOption) (*PopStashResponse, error)
	DropStash(ctx context.Context, in *DropStashRequest, opts ...grpc.CallOption) (*DropStashResponse, error)
	ShowStash(ctx context.Context, in *ShowStashRequest, opts ...grpc.CallOption) (*ShowStashResponse, error)
}

type gitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitServiceClient(cc grpc.ClientConnInterface) GitServiceClient {
	return &gitServiceClient{cc}
}

func (c *gitServiceClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GitService_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, GitService_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetCommitDetails(ctx context.Context, in *GetCommitDetailsRequest, opts ...grpc.CallOption) (*GetCommitDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitDetailsResponse)
	err := c.cc.Invoke(ctx, GitService_GetCommitDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetFileDiff(ctx context.Context, in *GetFileDiffRequest, opts ...grpc.CallOption) (*GetFileDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileDiffResponse)
	err := c.cc.Invoke(ctx, GitService_GetFileDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, GitService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, GitService_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ListRemotes(ctx context.Context, in *ListRemotesRequest, opts ...grpc.CallOption) (*ListRemotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemotesResponse)
	err := c.cc.Invoke(ctx, GitService_ListRemotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ListRemoteBranches(ctx context.Context, in *ListRemoteBranchesRequest, opts ...grpc.CallOption) (*ListRemoteBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemoteBranchesResponse)
	err := c.cc.Invoke(ctx, GitService_ListRemoteBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ExecuteDSL(ctx context.Context, in *ExecuteDSLRequest, opts ...grpc.CallOption) (*ExecuteDSLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteDSLResponse)
	err := c.cc.Invoke(ctx, GitService_ExecuteDSL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) DSLAutoComplete(ctx context.Context, in *DSLAutoCompleteRequest, opts ...grpc.CallOption) (*DSLAutoCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DSLAutoCompleteResponse)
	err := c.cc.Invoke(ctx, GitService_DSLAutoComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) StageFiles(ctx context.Context, in *StageFilesRequest, opts ...grpc.CallOption) (*StageFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageFilesResponse)
	err := c.cc.Invoke(ctx, GitService_StageFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) UnstageFiles(ctx context.Context, in *UnstageFilesRequest, opts ...grpc.CallOption) (*UnstageFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnstageFilesResponse)
	err := c.cc.Invoke(ctx, GitService_UnstageFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommitResponse)
	err := c.cc.Invoke(ctx, GitService_CreateCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetWorkingDiff(ctx context.Context, in *GetWorkingDiffRequest, opts ...grpc.CallOption) (*GetWorkingDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkingDiffResponse)
	err := c.cc.Invoke(ctx, GitService_GetWorkingDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, GitService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) Merge(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeResponse)
	err := c.cc.Invoke(ctx, GitService_Merge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, GitService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) DeleteBranch(ctx context.Context, in *DeleteBranchRequest, opts ...grpc.CallOption) (*DeleteBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBranchResponse)
	err := c.cc.Invoke(ctx, GitService_DeleteBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) Blame(ctx context.Context, in *BlameRequest, opts ...grpc.CallOption) (*BlameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlameResponse)
	err := c.cc.Invoke(ctx, GitService_Blame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetConflictDetails(ctx context.Context, in *GetConflictDetailsRequest, opts ...grpc.CallOption) (*GetConflictDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConflictDetailsResponse)
	err := c.cc.Invoke(ctx, GitService_GetConflictDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveConflictResponse)
	err := c.cc.Invoke(ctx, GitService_ResolveConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) AbortMerge(ctx context.Context, in *AbortMergeRequest, opts ...grpc.CallOption) (*AbortMergeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMergeResponse)
	err := c.cc.Invoke(ctx, GitService_AbortMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) IsMerging(ctx context.Context, in *IsMergingRequest, opts ...grpc.CallOption) (*IsMergingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMergingResponse)
	err := c.cc.Invoke(ctx, GitService_IsMerging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ListStashes(ctx context.Context, in *ListStashesRequest, opts ...grpc.CallOption) (*ListStashesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStashesResponse)
	err := c.cc.Invoke(ctx, GitService_ListStashes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) CreateStash(ctx context.Context, in *CreateStashRequest, opts ...grpc.CallOption) (*CreateStashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStashResponse)
	err := c.cc.Invoke(ctx, GitService_CreateStash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ApplyStash(ctx context.Context, in *ApplyStashRequest, opts ...grpc.CallOption) (*ApplyStashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyStashResponse)
	err := c.cc.Invoke(ctx, GitService_ApplyStash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) PopStash(ctx context.Context, in *PopStashRequest, opts ...grpc.CallOption) (*PopStashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopStashResponse)
	err := c.cc.Invoke(ctx, GitService_PopStash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) DropStash(ctx context.Context, in *DropStashRequest, opts ...grpc.CallOption) (*DropStashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropStashResponse)
	err := c.cc.Invoke(ctx, GitService_DropStash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) ShowStash(ctx context.Context, in *ShowStashRequest, opts ...grpc.CallOption) (*ShowStashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowStashResponse)
	err := c.cc.Invoke(ctx, GitService_ShowStash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServiceServer is the server API for GitService service.
// All implementations must embed UnimplementedGitServiceServer
// for forward compatibility.
type GitServiceServer interface {
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error)
	GetCommitDetails(context.Context, *GetCommitDetailsRequest) (*GetCommitDetailsResponse, error)
	GetFileDiff(context.Context, *GetFileDiffRequest) (*GetFileDiffResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	ListRemotes(context.Context, *ListRemotesRequest) (*ListRemotesResponse, error)
	ListRemoteBranches(context.Context, *ListRemoteBranchesRequest) (*ListRemoteBranchesResponse, error)
	ExecuteDSL(context.Context, *ExecuteDSLRequest) (*ExecuteDSLResponse, error)
	DSLAutoComplete(context.Context, *DSLAutoCompleteRequest) (*DSLAutoCompleteResponse, error)
	StageFiles(context.Context, *StageFilesRequest) (*StageFilesResponse, error)
	UnstageFiles(context.Context, *UnstageFilesRequest) (*UnstageFilesResponse, error)
	CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error)
	GetWorkingDiff(context.Context, *GetWorkingDiffRequest) (*GetWorkingDiffResponse, error)
	Push(context.Context, *PushRequest) (*PushResponse, error)
	Merge(context.Context, *MergeRequest) (*MergeResponse, error)
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	DeleteBranch(context.Context, *DeleteBranchRequest) (*DeleteBranchResponse, error)
	Blame(context.Context, *BlameRequest) (*BlameResponse, error)
	GetConflictDetails(context.Context, *GetConflictDetailsRequest) (*GetConflictDetailsResponse, error)
	ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error)
	AbortMerge(context.Context, *AbortMergeRequest) (*AbortMergeResponse, error)
	IsMerging(context.Context, *IsMergingRequest) (*IsMergingResponse, error)
	ListStashes(context.Context, *ListStashesRequest) (*ListStashesResponse, error)
	CreateStash(context.Context, *CreateStashRequest) (*CreateStashResponse, error)
	ApplyStash(context.Context, *ApplyStashRequest) (*ApplyStashResponse, error)
	PopStash(context.Context, *PopStashRequest) (*PopStashResponse, error)
	DropStash(context.Context, *DropStashRequest) (*DropStashResponse, error)
	ShowStash(context.Context, *ShowStashRequest) (*ShowStashResponse, error)
	mustEmbedUnimplementedGitServiceServer()
}

// UnimplementedGitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitServiceServer struct{}

func (UnimplementedGitServiceServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedGitServiceServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedGitServiceServer) GetCommitDetails(context.Context, *GetCommitDetailsRequest) (*GetCommitDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommitDetails not implemented")
}
func (UnimplementedGitServiceServer) GetFileDiff(context.Context, *GetFileDiffRequest) (*GetFileDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileDiff not implemented")
}
func (UnimplementedGitServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGitServiceServer) Pull(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedGitServiceServer) ListRemotes(context.Context, *ListRemotesRequest) (*ListRemotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemotes not implemented")
}
func (UnimplementedGitServiceServer) ListRemoteBranches(context.Context, *ListRemoteBranchesRequest) (*ListRemoteBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteBranches not implemented")
}
func (UnimplementedGitServiceServer) ExecuteDSL(context.Context, *ExecuteDSLRequest) (*ExecuteDSLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteDSL not implemented")
}
func (UnimplementedGitServiceServer) DSLAutoComplete(context.Context, *DSLAutoCompleteRequest) (*DSLAutoCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DSLAutoComplete not implemented")
}
func (UnimplementedGitServiceServer) StageFiles(context.Context, *StageFilesRequest) (*StageFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageFiles not implemented")
}
func (UnimplementedGitServiceServer) UnstageFiles(context.Context, *UnstageFilesRequest) (*UnstageFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnstageFiles not implemented")
}
func (UnimplementedGitServiceServer) CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommit not implemented")
}
func (UnimplementedGitServiceServer) GetWorkingDiff(context.Context, *GetWorkingDiffRequest) (*GetWorkingDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkingDiff not implemented")
}
func (UnimplementedGitServiceServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGitServiceServer) Merge(context.Context, *MergeRequest) (*MergeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Merge not implemented")
}
func (UnimplementedGitServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedGitServiceServer) DeleteBranch(context.Context, *DeleteBranchRequest) (*DeleteBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBranch not implemented")
}
func (UnimplementedGitServiceServer) Blame(context.Context, *BlameRequest) (*BlameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Blame not implemented")
}
func (UnimplementedGitServiceServer) GetConflictDetails(context.Context, *GetConflictDetailsRequest) (*GetConflictDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConflictDetails not implemented")
}
func (UnimplementedGitServiceServer) ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveConflict not implemented")
}
func (UnimplementedGitServiceServer) AbortMerge(context.Context, *AbortMergeRequest) (*AbortMergeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMerge not implemented")
}
func (UnimplementedGitServiceServer) IsMerging(context.Context, *IsMergingRequest) (*IsMergingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMerging not implemented")
}
func (UnimplementedGitServiceServer) ListStashes(context.Context, *ListStashesRequest) (*ListStashesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStashes not implemented")
}
func (UnimplementedGitServiceServer) CreateStash(context.Context, *CreateStashRequest) (*CreateStashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStash not implemented")
}
func (UnimplementedGitServiceServer) ApplyStash(context.Context, *ApplyStashRequest) (*ApplyStashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyStash not implemented")
}
func (UnimplementedGitServiceServer) PopStash(context.Context, *PopStashRequest) (*PopStashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PopStash not implemented")
}
func (UnimplementedGitServiceServer) DropStash(context.Context, *DropStashRequest) (*DropStashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropStash not implemented")
}
func (UnimplementedGitServiceServer) ShowStash(context.Context, *ShowStashRequest) (*ShowStashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowStash not implemented")
}
func (UnimplementedGitServiceServer) mustEmbedUnimplementedGitServiceServer() {}
func (UnimplementedGitServiceServer) testEmbeddedByValue()                    {}

// UnsafeGitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServiceServer will
// result in compilation errors.
type UnsafeGitServiceServer interface {
	mustEmbedUnimplementedGitServiceServer()
}

func RegisterGitServiceServer(s grpc.ServiceRegistrar, srv GitServiceServer) {
	// If the following call panics, it indicates UnimplementedGitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitService_ServiceDesc, srv)
}

func _GitService_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetCommitDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetCommitDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetCommitDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetCommitDetails(ctx, req.(*GetCommitDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetFileDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetFileDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetFileDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetFileDiff(ctx, req.(*GetFileDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ListRemotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListRemotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListRemotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListRemotes(ctx, req.(*ListRemotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ListRemoteBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemoteBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListRemoteBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListRemoteBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListRemoteBranches(ctx, req.(*ListRemoteBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ExecuteDSL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDSLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ExecuteDSL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ExecuteDSL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ExecuteDSL(ctx, req.(*ExecuteDSLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_DSLAutoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DSLAutoCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).DSLAutoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_DSLAutoComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).DSLAutoComplete(ctx, req.(*DSLAutoCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_StageFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).StageFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_StageFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).StageFiles(ctx, req.(*StageFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_UnstageFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnstageFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).UnstageFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_UnstageFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).UnstageFiles(ctx, req.(*UnstageFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_CreateCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).CreateCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_CreateCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).CreateCommit(ctx, req.(*CreateCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetWorkingDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkingDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetWorkingDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetWorkingDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetWorkingDiff(ctx, req.(*GetWorkingDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_Merge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).Merge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_Merge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).Merge(ctx, req.(*MergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_DeleteBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).DeleteBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_DeleteBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).DeleteBranch(ctx, req.(*DeleteBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_Blame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).Blame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_Blame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).Blame(ctx, req.(*BlameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetConflictDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConflictDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetConflictDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_GetConflictDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetConflictDetails(ctx, req.(*GetConflictDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ResolveConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ResolveConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ResolveConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ResolveConflict(ctx, req.(*ResolveConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_AbortMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).AbortMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_AbortMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).AbortMerge(ctx, req.(*AbortMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_IsMerging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMergingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).IsMerging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_IsMerging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).IsMerging(ctx, req.(*IsMergingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ListStashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStashesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListStashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ListStashes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListStashes(ctx, req.(*ListStashesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_CreateStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).CreateStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_CreateStash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).CreateStash(ctx, req.(*CreateStashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ApplyStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyStashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ApplyStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ApplyStash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ApplyStash(ctx, req.(*ApplyStashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_PopStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopStashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).PopStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_PopStash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).PopStash(ctx, req.(*PopStashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_DropStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropStashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).DropStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_DropStash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).DropStash(ctx, req.(*DropStashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_ShowStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowStashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ShowStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitService_ShowStash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ShowStash(ctx, req.(*ShowStashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitService_ServiceDesc is the grpc.ServiceDesc for GitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jock.GitService",
	HandlerType: (*GitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCommits",
			Handler:    _GitService_ListCommits_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _GitService_ListBranches_Handler,
		},
		{
			MethodName: "GetCommitDetails",
			Handler:    _GitService_GetCommitDetails_Handler,
		},
		{
			MethodName: "GetFileDiff",
			Handler:    _GitService_GetFileDiff_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GitService_GetStatus_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _GitService_Pull_Handler,
		},
		{
			MethodName: "ListRemotes",
			Handler:    _GitService_ListRemotes_Handler,
		},
		{
			MethodName: "ListRemoteBranches",
			Handler:    _GitService_ListRemoteBranches_Handler,
		},
		{
			MethodName: "ExecuteDSL",
			Handler:    _GitService_ExecuteDSL_Handler,
		},
		{
			MethodName: "DSLAutoComplete",
			Handler:    _GitService_DSLAutoComplete_Handler,
		},
		{
			MethodName: "StageFiles",
			Handler:    _GitService_StageFiles_Handler,
		},
		{
			MethodName: "UnstageFiles",
			Handler:    _GitService_UnstageFiles_Handler,
		},
		{
			MethodName: "CreateCommit",
			Handler:    _GitService_CreateCommit_Handler,
		},
		{
			MethodName: "GetWorkingDiff",
			Handler:    _GitService_GetWorkingDiff_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _GitService_Push_Handler,
		},
		{
			MethodName: "Merge",
			Handler:    _GitService_Merge_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _GitService_CreateBranch_Handler,
		},
		{
			MethodName: "DeleteBranch",
			Handler:    _GitService_DeleteBranch_Handler,
		},
		{
			MethodName: "Blame",
			Handler:    _GitService_Blame_Handler,
		},
		{
			MethodName: "GetConflictDetails",
			Handler:    _GitService_GetConflictDetails_Handler,
		},
		{
			MethodName: "ResolveConflict",
			Handler:    _GitService_ResolveConflict_Handler,
		},
		{
			MethodName: "AbortMerge",
			Handler:    _GitService_AbortMerge_Handler,
		},
		{
			MethodName: "IsMerging",
			Handler:    _GitService_IsMerging_Handler,
		},
		{
			MethodName: "ListStashes",
			Handler:    _GitService_ListStashes_Handler,
		},
		{
			MethodName: "CreateStash",
			Handler:    _GitService_CreateStash_Handler,
		},
		{
			MethodName: "ApplyStash",
			Handler:    _GitService_ApplyStash_Handler,
		},
		{
			MethodName: "PopStash",
			Handler:    _GitService_PopStash_Handler,
		},
		{
			MethodName: "DropStash",
			Handler:    _GitService_DropStash_Handler,
		},
		{
			MethodName: "ShowStash",
			Handler:    _GitService_ShowStash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jock.proto",
}
